### ISSUE TITLE
Add units

### ISSUE THREAD

**Issue by markulrich** [SEOLteam/ode-tutorial2#16]
kg, m, N/m

**Comment by candicemurray** [comment]
I looked up units for spring constants.  It looks like typical values range from about .1 N/m to 500 N/m... let's go for a middle range and keep it 1 to 100 like it is now.  Would it be possible to have the slider in increments of 2 or 5 instead of 10 though?

**Comment by markulrich** [comment]
Sounds good!

**Comment by markulrich** [comment]
Do you think step of 1 would be good? Or should we do 2/5 and change the min to be 2/5? Whatever you think is best, just that min should probably match step size.

**Comment by candicemurray** [comment]
One should be fine!
