### ISSUE TITLE
Physical and user-friendly ranges of k,m, and amplitude

### ISSUE THREAD

**Issue by conantee** [SEOLteam/ode-tutorial2#22]
For amplitude, the range should be from zero to 1/4 of ruler (assuming that ruler is full iframe width and equilibrium is in the middle).

For k, the range should be from 1 N/m to 100 N/m

For m, the range should be from 1 to 10 kg. Object radius should scale by cube root of mass.

**Comment by haichuanyu** [comment]
Notes:
A: Range value done, position in progress
k: range done
m: range done, scaling done

Ruler:
- Scale is fixed regardless of window size
- 1 cm corresponds to 57 pixels
-- 5 cm (tick to tick) corresponds to 286 pixels
- Assume from an iFrame we will be able to see between 12-16 cm
- So our range should be 3-4 cm amplitude

**Comment by haichuanyu** [comment]
Ah - it's clear now.

The page loads with the mass at its maximum extension (its amplitude). When you release the mass, the position is recorded from the true equilibrium yielding the amplitude.

The page should load with the mass at equilibrium. We can drag the mass and release it, and the amplitude should be recorded. This dragging should be bounded by +/- 4 cm. 

So landing at the page, we should not be able to 'see' the amplitude based on the ball position; only the number A should inform us of the amplitude.

Maybe we can have some lines to mark the expected amplitude instead. (Visibility of system status).

**Comment by markulrich** [comment]
I think the current plan is to replace the ruler with just an unmarked grid in the background?

**Comment by haichuanyu** [comment]
That might solve part of the problem. What about the ball's starting position?

**Comment by markulrich** [comment]
I added the grid. Don't think I was around for the ball's starting position conversation. I made a version where ball starts at 0 (and 'START' button instead says 'DRAG MASS') - does that sound good?

**Comment by haichuanyu** [comment]
Maybe. Can you show me? I'm a bit confused about the start button, esp. since I made a mod in one of my branches. Let's meet to see.

**Comment by conantee** [comment]
By the way, could you change "K" in simulation to be lower case "k".

**Comment by markulrich** [comment]
k is lowercase now. Anything more specific to this ticket or can we close it?

**Comment by conantee** [comment]
I think we are good for now.
