### ISSUE TITLE
Make ruler start at 0, have negative numbers

### ISSUE THREAD

**Issue by markulrich** [SEOLteam/ode-tutorial2#7]

**Comment by markulrich** [comment]
Add line to follow ruler

**Comment by haichuanyu** [comment]
made the ruler generator output negative numbers:
https://github.com/haichuanyu/VectorRuler

- how can we align the ruler and the ball's resting position?

**Comment by haichuanyu** [comment]
Here's the tool to generate it straight up: 

http://robbbb.github.io/VectorRuler/

Robbbb merged my edit.
